version: '3.9'

services:
  postgres:
    image: postgres:16

    container_name: hes_postgres

    restart: always

    environment:
      POSTGRES_USER: hes_admin
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: hes_management

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: